### ISSUE TITLE
Closure Turned Static Breaks Code

### ISSUE THREAD

**Issue by XedinUnknown** [inpsyde/php-coding-standards#46]
## The Problem
After [this change][1], I started receiving warnings like the following:

```
Warning: Cannot bind an instance to a static closure in /var/www/html/wp-content/plugins/translationmanager/src/Project/Taxonomy.php on line 72
```

Predictably, this also causes fatal errors down the line:

```
Fatal error: Uncaught Error: Function name must be a string in /var/www/html/wp-content/plugins/translationmanager/src/Project/Taxonomy.php:75
--
  | Stack trace:
  | #0 /var/www/html/wp-includes/class-wp-hook.php(288): Translationmanager\Project\Taxonomy->project_form(Object(Translationmanager\TableList\ProjectItem))
  | #1 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
  | #2 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
  | #3 /var/www/html/wp-content/plugins/translationmanager/src/TableList/ProjectItem.php(171): do_action('translationmana...', Object(Translationmanager\TableList\ProjectItem))
  | #4 /var/www/html/wp-content/plugins/translationmanager/views/project/page-layout.php(13): Translationmanager\TableList\ProjectItem->views()
  | #5 /var/www/html/wp-content/plugins/translationmanager/src/Pages/Project.php(112): require_once('/var/www/html/w...')
  | #6 /var/www/html/wp-includes/class-wp-hook.php(288): Translationmanager\Pages\Project->render_template('')
  | #7 /var/www/html/wp-includes/cl in /var/www/html/wp-content/plugins/translationmanager/src/Project/Taxonomy.php on line 75
```

## Possible Cause
When using PHPCBF, one of the snifs turns all or most closures `static`. Static closures are slightly cheaper, but don't allow binding. It appears that the sniff in question is `Inpsyde.CodeQuality.StaticClosure`.

## Remarks
- How does the sniff determine whether or not to make a closure `static`?
- How can I prevent closures that need to be bound from becoming `static`?

[1]: https://github.com/inpsyde/translationmanager/commit/da695f15c08d521b222c7b750ac46fb22f108a3e#diff-adeeb2c1927841087006891e196b3890213d68f06d9135c995dfaa558a9455afR67

**Comment by XedinUnknown** [comment]
As @gmazzap has explained to be, to make a closure explicitly bindable, use the new `@bound` annotation, like so:

```php
/** @bound */
$cl = function () { echo "Hello" }
```
